### ISSUE TITLE
Share SCSS variables with js

### ISSUE THREAD

**Issue by rosalynpoort** [michaelsoriano/barebones#2]
hi, thank you for this starter theme! I am using it with sass and would like to know how I can export sass variables to access in the js. I found this info --

https://til.hashrocket.com/posts/sxbrscjuqu-share-scss-variables-with-javascript

but it isn't working with this theme and I'm wondering if there needs to be some kind of web pack config options?

any help would be greatly appreciated, thank you!

**Comment by michaelsoriano** [comment]
I'm not sure how to integrate SCSS. A better person to answer this would be @devloco - the creator of create-react-wptheme => https://github.com/devloco/create-react-wptheme. You can post the issue there. He usually responds right away.
